[theme]
base="light"
primaryColor="#0369A1"             # Derin Mavi: Gri ve beyazın üzerinde çok şık durur, butonların ve önemli verilerin anında göze çarpmasını sağlar.
backgroundColor="#FFFFFF"          # Saf Beyaz: Arkaplandaki çizgilerin tabloları ve metinleri boğmasını engeller, tertemiz bir okuma alanı sunar.
secondaryBackgroundColor="#F8FAFC" # Buzlu Beyaz/Gri: Yan menü ve veri giriş kutularını ana beyaz alandan hafifçe ayırır.
textColor="#1E293B"                # Koyu Füme: Saf siyahın göz yoruculuğunu alır, ekranda kaliteli bir mürekkep gibi okunaklı durur.
font="sans serif"
